import type { Metadata } from "next";
import { Joan } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import { LanguageProvider } from "@/providers/LanguageProvider";

const joanSans = Joan({
  variable: "--font-joan",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${joanSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col px-2.5 md:px-5">
        <LanguageProvider>
          <Header />
          <div className="mt-30">{children}</div>
        </LanguageProvider>
      </body>
    </html>
  );
}
